### ISSUE TITLE
Refactor status `next` and `previous` attributes from `set` to `list`

### ISSUE THREAD

**Issue by rafaelcassau** [lamenezes/status-map#1]
Status class `next` and `previous` attributes are `set` objects, when `StatusMap` process these attributes the order are ignored and this operation can result in unexpected behavior:

```python
StatusMap({
        "": ("created", "sent"),
        "created": ("sent", "sent_error"),
        "sent": ("published", "rejected"),
        "sent_error": ("created",),
        "rejected": ("sent",),
        "published": ("rejected",),
    })
```
This example has some status linked one with other, ex: `created -> sent_error -> created`, `sent -> rejected -> sent`, this kind of relationship can cause unexpected behaviour if order of the values are ignored, resulting is a `StatusMap` with `previous` and `next` wrong relationship.

**Comment by lamenezes** [comment]
Thx for submitting the issue and solving it! :birthday:
